version: '2.1'

services:

  straxui_app:
    build: https://github.com/jmosbacher/straxui.git
    command: bokeh serve straxui --allow-websocket-origin=localhost
    container_name: straxui_app
    depends_on:
      - straxrpc_server
    # env_file:
    #  - ./sc_reader/sc.env
    ports:
      - 5006:5006
    volumes:
      - ../straxui/straxui:/code/straxui
    
    links:
      - straxrpc_server
      - nginx
    #restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - default
    environment:
      - STRAXRPC_ADDR=straxrpc_server:50051

  straxrpc_server:
    build: ./straxrpc_server
    command: python run_server.py
    container_name: straxrpc_server
    volumes:
      - ./straxrpc_server/run_server.py:/code/run_server.py
      - ./custom_data:/custom_data
    ports:
      - 50051:50051
    stdin_open: true
    tty: true
    networks:
      - default
    
  nginx:
    image: nginx:latest
    container_name: production_nginx
    # depends_on:
    #   - straxui_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
      
    networks:
      - default
    restart: on-failure

networks:
  default:
    # labels:
    #   - com.docker.lb.hosts=default.local
    #   - com.docker.lb.port=5006
    #   - com.docker.lb.websocket_endpoints=/straxui/ws
     
